# This workflow will run cypress tests

# If you change this name, don't forget to change deploy-to-alpha.yml
name: Cypress tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  # This identifier gets used in .mergify.yml
  cypress:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install Python dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install -r requirements.txt
    - name: Install Nodejs dependencies
      run: |
        npm ci
    - name: Run the deploy script and prepare the dev database
      run: |
        doit run deploy devdb

    - name: Bundle files
      # Generates js and css files.
      run: |
        build-tools/heroku/tailwind/generate-development-css
        build-tools/heroku/generate-typescript

    - name: Start the server
      # Runs in the background
      run: build-tools/github/start-debug-server --daemon

    - name: Cypress run
      uses: cypress-io/github-action@v6
      with:
        # We have already installed all dependencies
        install: false
        # Record to cypress cloud to inspect possible failing tests.
        record: true
        # Where cypress.config.js and all the other cypress files live, requires 'install: false'
        working-directory: tests/
      env:
        # pass the Cypress Cloud record key as an environment variable
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
        # pass GitHub token to allow accurately detecting a build vs a re-run build
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

