name: Automatically deploy to Alpha
on:
  # Run this AFTER the unit test job finishes
  workflow_run:
    # Must be the same as in unittests.yml, cypresstests.yml
    workflows: ["Unit tests", "Cypress tests"]
    branches: [main]
    types:
      - completed
jobs:
  deploy:
    # Deploy ONLY IF the tests actually succeeded (if they failed, we don't wanna deploy)
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: hedy-alpha
          heroku_email: felienne@gmail.com
